**Ana Belén López Pérez**

# VY University 
# Ejercicio Práctico Python - Data Engineering

**Instrucciones Generales:**

* **Código limpio y bien documentado**: Asegúrate de que tu código sea claro, legible, esté bien estructurado e incluye comentarios explicativos cuando sea necesario. Si usas funciones, asegúrate de que están bien documentadas (`docstring`).

* **Ejecutabilidad**: Todo lo que incluyas en este notebook deberá ser completamente ejecutable sin errores. Antes de enviar tu trabajo, revisa y asegúrate de que todas las celdas se ejecutan correctamente en el orden en el que están presentadas.

* **Evaluación**: Se evaluará todo el contenido enviado en este archivo `.ipynb`, incluyendo cualquier código que no esté directamente relacionado con la respuesta a los ejercicios, además de la robustez del código con errores controlados. Asegúrate de que no haya celdas innecesarias o con errores de ejecución. Asegúrate también de indicar la respuesta a cada pregunta (ejemplo, si creas una función, que hagas la llamada con el output esperado).

Recuerda seguir las instrucciones adicionales que se den en cada pregunta y utilizar las técnicas que consideres más eficientes para cada solución. 

**¡Buena suerte!🍀**

## PARTE A – Python nativo

**⚠️ Importante ⚠️**

* **Uso de librerías**: En esta parte, solo se permite el uso de **<u>Python nativo</u>**. No se pueden importar módulos externos, como `pandas`, `numpy`, u otros. Todos los ejercicios deben resolverse utilizando únicamente las herramientas y funciones que Python proporciona de manera nativa.

### Pregunta A-1: Encontrar el número máximo en una lista

Define una función en Python que **itere sobre los elementos de una lista de números** y devuelva **el número más grande de la lista**, **sin utilizar la función integrada `max()`**.

La función debe manejar correctamente los siguientes casos:
- Listas con números positivos y negativos.  
- Listas vacías (debe devolver `None` o un mensaje indicativo).  
- Listas que contengan valores no numéricos (deben ignorarse).

**Listas de prueba:**
```python
list_1 = [-4, -60, 5, 30, 30, 150]
list_2 = [10, 20, 5, 30, 40, 107]
list_3 = []
list_4 = [10, "hola", 5, None]

In [1]:
#resolvemos el ejercicio definiendo nuestra función
def encontrar_maximo(lista):
    maximo = None

    for elemento in lista:
        if isinstance(elemento, (int, float)): #observamos si el elemento es int o float
            if maximo is None or elemento > maximo:
                maximo = elemento

    return maximo


#pasamos las listas de pruebas que nos vienen dadas
list_1 = [-4, -60, 5, 30, 30, 150]
list_2 = [10, 20, 5, 30, 40, 107]
list_3 = []
list_4 = [10, "hola", 5, None]

# sacamos el resultado por pantalla
print("Máximo list_1:", encontrar_maximo(list_1))
print("Máximo list_2:", encontrar_maximo(list_2))
print("Máximo list_3:", encontrar_maximo(list_3))
print("Máximo list_4:", encontrar_maximo(list_4))

Máximo list_1: 150
Máximo list_2: 107
Máximo list_3: None
Máximo list_4: 10

### Pregunta A-2: Encuentra el número que falta

Define una función en Python que, dada una lista de números enteros consecutivos del **1 al n**, encuentre **el número que falta** (asumiendo que siempre falta exactamente **un solo número**).

**Lista de prueba:**
```python
list_1 = [1, 5, 6, 3, 4]
```
(es decir, tu función debe encontrar el número 2 en la lista de prueba)

> 💡 **Pista**: Puedes suponer que todos los números son enteros positivos y no se repiten.

In [2]:
#generamos nuesta función 
def encontrar_faltante(lista):
    lista.sort()  

    numero_esperado = 1

    for numero in lista:
        if numero != numero_esperado:
            return numero_esperado
        numero_esperado += 1


#añadimos la lista de prueba que nos viene dada
list_1 = [1, 5, 6, 3, 4]

#ejecutamos la función y la imprimimos por pantalla
resultado = encontrar_faltante(list_1)
print("El número que falta es:", resultado)

El número que falta es: 2

### Pregunta A-3: Palíndromos

Corrige y completa la función `find_palindromic()` para que, dada una lista de palabras, la función retorne una **lista con aquellas palabras que son palíndromas**.

(Un **palíndromo** es una palabra, frase o número que se lee igual de izquierda a derecha que de derecha a izquierda).

> 💡 **Pista**: word[::-1]

**Lista de prueba:**
```python
lista = ["ahora", "hola", "oso", "Mexico", "Rojo", "Ana", "rador", "Omar", "arroz"]
```

In [3]:
def find_palindromic(words):
    palindromes = []
    for word in words:
        #comparamos en minúsculas para que interprete como palindromos independientemente si viene con mayúscula
        if word.lower() == word.lower()[::-1]:
            palindromes.append(word)
    return palindromes

#añadimos nuestra lista
lista = ["ahora", "hola", "oso", "Mexico", "Rojo", "Ana", "rador", "Omar", "arroz"]

#sacamos el resultado por pantalla
print(find_palindromic(lista))

['oso', 'Ana']

### Pregunta A-4: Dividir una lista en sublistas equilibradas

Escribe una función en Python que divida una lista de números en **N sublistas** lo más equilibradas posible.  
Si la longitud de la lista no es divisible exactamente por N, algunas sublistas pueden tener **un elemento más** que otras. El objetivo es **minimizar la diferencia de tamaño** entre las sublistas.

**Instrucciones:**

Define una función `solve(lista, N)` que reciba los siguientes argumentos:

- `lista`: una lista de números.  
- `N`: un número entero que indica en cuántas partes (sublistas) se quiere dividir la lista.

La función debe devolver una **lista de sublistas**, donde cada sublista contenga una porción de los elementos de la lista original. La implementación debe asegurar que la diferencia de tamaño entre las sublistas sea mínima.

Tu código debe funcionar con listas vacías o cuando `N` sea mayor que la longitud de la lista.

> 💡 **Pista**: Piensa en cómo distribuir los elementos de la lista de forma equilibrada usando operaciones matemáticas simples.

**Casos de ejemplo:**

**Ejemplo 1**

Entrada:
```python
lista_1 = [1, 2, 3, 4, 5, 6, 7]
N = 3
```

Salida esperada:
```python
[[1, 2, 3], [4, 5], [6, 7]]
```

**Ejemplo 2**

Entrada:
```python
lista_2 = [10, 20, 30, 40, 50]
N = 2
```

Salida esperada:
```python
[[10, 20, 30], [40, 50]]
```

**Ejemplo 3**

Entrada:
```python
lista_3 = [8, 12]
N = 5
```

Salida esperada:
```python
[[8], [12], [], [], []]
```

**Ejemplo 4**

Entrada:
```python
lista_4 = []
N = 5
```

Salida esperada:
```python
[[], [], [], [], []]
```

In [4]:
import random #para generar la lista aleatoria

# lista con número aleatorios
lista = [random.randint(1, 100) for _ in range(10)]
N = 3

def solve(lista, N):
    result = []
    start = 0
    length = len(lista)
    for i in range(N):
        size = length // N + (1 if i < length % N else 0)
        result.append(lista[start:start+size])
        start += size
    return result
#imprimimos por pantalla las soluciones que se solicitan
print("Lista original:", lista)
print("Sublistas:", solve(lista, N))

Lista original: [11, 51, 77, 71, 73, 93, 66, 38, 73, 89]
Sublistas: [[11, 51, 77, 71], [73, 93, 66], [38, 73, 89]]

## PARTE B – Librerías externas

**⚠️ Importante ⚠️**

* **Uso de librerías**: En esta parte, sí se permite importar módulos externos, como `pandas`, `numpy`, u otros.

In [5]:
# Importa tus librerías aquí ⬇️
import numpy as np
import pandas as pd

### Pregunta B-1: Análisis estadístico con NumPy
Usando la librería **NumPy**, crea un array con los siguientes valores:

```python
[12, 18, 25, 30, 22, 15, 40, 33, 28, 10]
```
Realiza las siguientes operaciones:
1. Calcula la **media, mediana y desviación estándar**.
2. Filtra y muestra únicamente los valores **mayores que la media.**
3. Muestra todos los resultados por pantalla con un formato claro.

In [6]:
#metemos los datos en un array
valores = np.array([12, 18, 25, 30, 22, 15, 40, 33, 28, 10])

In [7]:
# 1. hacemos los calculos
media = np.mean(valores)
mediana = np.median(valores)
desviacion = np.std(valores)

# y los mostramos por pantalla 
print (media)
print(mediana)
print (desviacion)

23.3
23.5
9.198369420718

In [8]:
# 2. Filtramos los valores mayores a la media
mayores_que_media = valores[valores > media]

print(mayores_que_media)

[25 30 40 33 28]

In [9]:
#lo mostramos con un formato claro

df_resultados = pd.DataFrame({
    "Valores": valores,
    "Mayor_que_media": [v if v > media else "" for v in valores]  # dejamos en blanco la celda y solo se muestra cuando es mayor que la media
})

print("\n=== ¿Qué valores son mayor a la media? ===")
df_resultados

=== ¿Qué valores son mayor a la media? ===

   Valores Mayor_que_media
0       12
1       18
2       25              25
3       30              30
4       22
5       15
6       40              40
7       33              33
8       28              28
9       10

In [10]:
# hacemos otro df con todos los datos ya que el de mayores que la media puede resultar confuso 
df_estadisticas = pd.DataFrame({
    "Media": [media],
    "Mediana": [mediana],
    "Desviación_Estándar": [desviacion]
})

In [11]:
print("\n=== Estadísticas ===")
df_estadisticas

=== Estadísticas ===

   Media  Mediana  Desviación_Estándar
0   23.3     23.5             9.198369

### Pregunta B-2: Limpieza de datos con Pandas

Crea un `DataFrame` con los siguientes datos:

| vuelo_id | aerolinea | retraso_min | duracion_min |
|-----------|------------|--------------|---------------|
| 1         | Ryanair    | 10           | 130           |
| 2         | Ryanair    | -3           | 125           |
| 3         | EasyJet    | NaN          | 145           |
| 4         | EasyJet    | 20           | 140           |
| 5         | Vueling    | 15           | NaN           |
| 6         | Vueling    | -8           | 160           |

**Tareas:**
1. Crea el DataFrame con los datos anteriores.  
2. Calcula la **media de retraso por aerolínea**, considerando solo valores válidos (no nulos ni negativos).  
3. Sustituye los valores **negativos** en la columna `retraso_min` por la **media de retraso** de la aerolínea correspondiente.  
4. Elimina las filas que contengan valores nulos (`NaN`) en cualquier columna.  
5. Crea una nueva columna llamada `retraso_ajustado` con los valores corregidos.  
6. Calcula y muestra el **retraso medio por aerolínea (ajustado)**.  
7. Muestra el **DataFrame final** limpio y corregido.

**Requisitos:**
- No se permite imputar manualmente valores.  
- El DataFrame final debe conservar la estructura original (sin índices reiniciados).

Output esperado:
```markdown
Retraso medio por aerolínea (ajustado):
aerolinea
EasyJet    20.0
Ryanair    10.0
Vueling    15.0
Name: retraso_ajustado, dtype: float64

DataFrame limpio y corregido:
   vuelo_id aerolinea  retraso_min  duracion_min  retraso_ajustado
0         1   Ryanair         10.0         130.0              10.0
1         2   Ryanair         -3.0         125.0              10.0
3         4   EasyJet         20.0         140.0              20.0
5         6   Vueling         -8.0         160.0              15.0
```

**1. Creamos el Dataframe**

In [12]:
#aquí haríamos el import pandas y numpy, pero lo tenemos unas celdas más arribla

#ceramos nuestro dataframe directamente lo llamaremos infovuelos
infovuelos = pd.DataFrame({
    "vuelo_id": [1, 2, 3, 4, 5, 6],
    "aerolinea": ["Ryanair", "Ryanair", "EasyJet", "EasyJet", "Vueling", "Vueling"],
    "retraso_min": [10, -3, np.nan, 20, 15, -8],
    "duracion_min": [130, 125, 145, 140, np.nan, 160]
})

#sacamos el df por pantalla
print(infovuelos)

   vuelo_id aerolinea  retraso_min  duracion_min
0         1   Ryanair         10.0         130.0
1         2   Ryanair         -3.0         125.0
2         3   EasyJet          NaN         145.0
3         4   EasyJet         20.0         140.0
4         5   Vueling         15.0           NaN
5         6   Vueling         -8.0         160.0

In [13]:
#lo vamos a mostrar más bonito
print("\n=== Inormación sobre el retraso de vuelos de las diferentes compañías ===")
infovuelos

=== Inormación sobre el retraso de vuelos de las diferentes compañías ===

   vuelo_id aerolinea  retraso_min  duracion_min
0         1   Ryanair         10.0         130.0
1         2   Ryanair         -3.0         125.0
2         3   EasyJet          NaN         145.0
3         4   EasyJet         20.0         140.0
4         5   Vueling         15.0           NaN
5         6   Vueling         -8.0         160.0

**2. Media de retrasos por aerolínea**

In [14]:
# quitamos los nulos y los numero negativos de los retrasos para obtener los datos con los que podemos trabajar
retrasos_validos = infovuelos[infovuelos['retraso_min'].notna() & (infovuelos['retraso_min'] >= 0)]

# hacemos otro df calculando la media de restrasos de cada aeroline
media_retraso = retrasos_validos.groupby('aerolinea')['retraso_min'].mean()

# Mostrar resultados
print("\n=== Minutos de media de retraso ===")
media_retraso

=== Minutos de media de retraso ===

aerolinea
EasyJet    20.0
Ryanair    10.0
Vueling    15.0
Name: retraso_min, dtype: float64

**3. Sustituir los valores negativos por la media de retraso**

In [18]:
def reemplazar_negativos(row):
    if row['retraso_min'] < 0 or pd.isna(row['retraso_min']):
        return media_retraso[row['aerolinea']]
    else:
        return row['retraso_min']

# no tocamos el df original y tenemos uno con una nueva columna de retraso ajustado
infovuelos_reemplazo = infovuelos.copy()

# Añadimos la columna de retraso ajustado
infovuelos_reemplazo['retraso_ajustado'] = infovuelos_reemplazo.apply(reemplazar_negativos, axis=1)

In [19]:
infovuelos_reemplazo

   vuelo_id aerolinea  retraso_min  duracion_min  retraso_ajustado
0         1   Ryanair         10.0         130.0              10.0
1         2   Ryanair         -3.0         125.0              10.0
2         3   EasyJet          NaN         145.0              20.0
3         4   EasyJet         20.0         140.0              20.0
4         5   Vueling         15.0           NaN              15.0
5         6   Vueling         -8.0         160.0              15.0

In [20]:
#eliminamos la columna anterior 
infovuelos_reemplazo = infovuelos_reemplazo.drop(columns=['retraso_min'])

In [21]:
infovuelos_reemplazo

   vuelo_id aerolinea  duracion_min  retraso_ajustado
0         1   Ryanair         130.0              10.0
1         2   Ryanair         125.0              10.0
2         3   EasyJet         145.0              20.0
3         4   EasyJet         140.0              20.0
4         5   Vueling           NaN              15.0
5         6   Vueling         160.0              15.0

In [16]:
#comprobamos que se muestra en nuestro df correctamente
infovuelos

   vuelo_id aerolinea  retraso_min  duracion_min
0         1   Ryanair         10.0         130.0
1         2   Ryanair         -3.0         125.0
2         3   EasyJet          NaN         145.0
3         4   EasyJet         20.0         140.0
4         5   Vueling         15.0           NaN
5         6   Vueling         -8.0         160.0

**4. Eliminamos valores NaN**

In [24]:
#eliminamos los NaN
infovuelos = infovuelos.dropna()

#comprobamos
infovuelos

   vuelo_id aerolinea  retraso_min  duracion_min  retraso_ajustado
0         1   Ryanair         10.0         130.0              10.0
1         2   Ryanair         -3.0         125.0              10.0
3         4   EasyJet         20.0         140.0              20.0
5         6   Vueling         -8.0         160.0              15.0

**4. Añadimos columna del retraso ajustado**

In [28]:
#añadimos la columna restraso ajustado a nuestro dataframe 


infovuelos['retraso_ajustado'] = infovuelos_reemplazo['retraso_ajustado']


infovuelos

C:\Users\Ana Belén\AppData\Local\Temp\ipykernel_11740\712587784.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  infovuelos['retraso_ajustado'] = infovuelos_reemplazo['retraso_ajustado']

   vuelo_id aerolinea  retraso_min  duracion_min  retraso_ajustado
0         1   Ryanair         10.0         130.0              10.0
1         2   Ryanair         -3.0         125.0              10.0
3         4   EasyJet         20.0         140.0              20.0
5         6   Vueling         -8.0         160.0              15.0

**5. Mostrar media de retraso por aerolínea**

In [35]:
# Media de retraso ajustado por aerolínea
retraso_medio_por_aerolinea = infovuelos.groupby('aerolinea')['retraso_ajustado'].mean()

# Mostrar el resultado
print(retraso_medio_por_aerolinea)

aerolinea
EasyJet    20.0
Ryanair    10.0
Vueling    15.0
Name: retraso_ajustado, dtype: float64

In [38]:
print(infovuelos)

   vuelo_id aerolinea  retraso_min  duracion_min  retraso_ajustado
0         1   Ryanair         10.0         130.0              10.0
1         2   Ryanair         -3.0         125.0              10.0
3         4   EasyJet         20.0         140.0              20.0
5         6   Vueling         -8.0         160.0              15.0

**6. Dataframe final**

In [37]:
infovuelos

   vuelo_id aerolinea  retraso_min  duracion_min  retraso_ajustado
0         1   Ryanair         10.0         130.0              10.0
1         2   Ryanair         -3.0         125.0              10.0
3         4   EasyJet         20.0         140.0              20.0
5         6   Vueling         -8.0         160.0              15.0